# Generated by Django 4.0.2 on 2022-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('current_quantity', models.FloatField(max_length=250)),
                ('quantity_threshold', models.FloatField(max_length=250)),
                ('metric', models.CharField(choices=[('kg', 'kilogram'), ('mg', 'milligram'), ('g', 'gram')], default='kg', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
