# Generated by Django 4.0.3 on 2022-03-26 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_expiration_date_ingredient_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
