# Generated by Django 4.0.3 on 2022-03-26 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
