# Generated by Django 4.0.3 on 2022-05-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
    ]
