# Generated by Django 4.0.3 on 2022-05-24 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredient_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_threshold', models.FloatField(max_length=250)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
            ],
        ),
    ]
