# Generated by Django 4.0.3 on 2022-05-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_ingredientbatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientbatch',
            old_name='quantity_threshold',
            new_name='quantity',
        ),
    ]
