# Generated by Django 4.0.3 on 2022-05-24 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_rename_quantity_threshold_ingredientbatch_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientbatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
