# Generated by Django 4.0.3 on 2022-03-02 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('emailaddress', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 2, 21, 57, 47, 326612), editable=False)),
            ],
        ),
    ]
