# Generated by Django 4.0.3 on 2022-03-02 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 22, 11, 34, 589100), editable=False),
        ),
    ]
