# Generated by Django 4.0.3 on 2022-03-02 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_date_alter_supplier_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 22, 13, 46, 121607), editable=False),
        ),
    ]
