# Generated by Django 2.0 on 2022-04-15 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_auto_20220415_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 19, 16, 14, 61380), editable=False),
        ),
    ]
