# Generated by Django 4.0.4 on 2022-04-16 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_alter_supplier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 22, 55, 3, 256851), editable=False),
        ),
    ]
