# Generated by Django 4.0.3 on 2022-04-24 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0024_alter_supplier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 20, 13, 11, 609331), editable=False),
        ),
    ]
