# Generated by Django 4.0.3 on 2022-05-21 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0027_alter_supplier_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 14, 25, 5, 761185), editable=False),
        ),
    ]
