# Generated by Django 4.0.4 on 2022-04-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_id'),
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_order',
        ),
        migrations.AddField(
            model_name='order',
            name='ingredient_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
            preserve_default=False,
        ),
    ]
