# Generated by Django 4.0.4 on 2022-04-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
    ]
