# Generated by Django 4.0.4 on 2022-04-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_payment_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
