# Generated by Django 4.0.4 on 2022-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('served', 'Served')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
