# Generated by Django 4.0.3 on 2022-05-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_ingredient_id'),
        ('orders', '0011_remove_order_product_order_order_ingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ingredient_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
    ]
