# Generated by Django 4.0.3 on 2022-05-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_remove_ingredient_created_at'),
        ('orders', '0012_alter_order_ingredient_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ingredient_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('quantity', models.IntegerField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
